// GET /accounts/:accountId/invitations  — list pending invitations.
// POST /accounts/:accountId/invitations — create a new invitation.
//
// Authorization:
//   - GET: any active member (default-read on account-scoped resources).
//   - POST: team.invite permission (teamAdmin only per PA-201 matrix).
//
// Token format: 32 bytes hex (64 chars), generated by crypto.randomBytes(32).
// 7-day expiry. Tokens are stored in plaintext (hashing deferred to v1.5,
// filed in TODOS.md).

import { NextRequest, NextResponse } from "next/server";
import { getAuthenticatedCustomer } from "@/lib/auth/helpers";
import { requirePermission } from "@/lib/auth/audit";
import { materializeImplicitOwner } from "@/lib/auth/membership";
import { prisma } from "@/lib/prisma";
import {
  PACKET_ROLES,
  ROLE_PERMISSIONS,
  type PacketRole,
} from "@/lib/auth/role-permissions";
import { randomBytes } from "crypto";
import { sendTeamInviteEmail } from "@/lib/email/templates/team-invite";

const INVITATION_TTL_DAYS = 7;

// Bounded by team_invitation.invitee_name (VarChar 255). We cap below the
// column limit because (a) 100 chars is already absurd for a human name and
// (b) anything past the column limit makes Prisma throw a non-JSON 500
// (PA-225).
const MAX_INVITEE_NAME_LEN = 100;
// RFC 5321 caps email at 254 chars. Anything longer is junk input.
const MAX_EMAIL_LEN = 254;

function isPacketRole(role: string): role is PacketRole {
  return (PACKET_ROLES as readonly string[]).includes(role);
}

interface RouteContext {
  params: Promise<{ accountId: string }>;
}

export async function GET(request: NextRequest, { params }: RouteContext) {
  const auth = await getAuthenticatedCustomer(request);
  if (auth instanceof NextResponse) return auth;

  const { accountId } = await params;
  if (accountId !== auth.accountId) {
    return NextResponse.json(
      { error: "You do not have access to this account." },
      { status: 403 },
    );
  }

  const invitations = await prisma.teamInvitation.findMany({
    where: { stripeCustomerId: accountId, status: "pending" },
    orderBy: { createdAt: "desc" },
  });

  // Don't leak the raw token in list responses — clients only see truncated.
  // The full token is only ever returned at creation time.
  return NextResponse.json({
    invitations: invitations.map((i) => ({
      id: i.id,
      email: i.email,
      role: i.role,
      roleDisplayName: isPacketRole(i.role)
        ? ROLE_PERMISSIONS[i.role].displayName
        : i.role,
      invitedAt: i.createdAt.toISOString(),
      expiresAt: i.expiresAt.toISOString(),
      tokenPreview: i.token.slice(0, 8),
    })),
  });
}

export async function POST(request: NextRequest, { params }: RouteContext) {
  const auth = await getAuthenticatedCustomer(request);
  if (auth instanceof NextResponse) return auth;

  const { accountId } = await params;
  if (accountId !== auth.accountId) {
    return NextResponse.json(
      { error: "You do not have access to this account." },
      { status: 403 },
    );
  }

  const denial = requirePermission(auth, "team.invite", request);
  if (denial) return denial;

  const body = (await request.json().catch(() => ({}))) as {
    email?: string;
    role?: string;
    inviteeName?: string;
  };
  const email = body.email?.trim().toLowerCase();
  const role = body.role;
  const inviteeName = body.inviteeName?.trim() || null;

  if (!email || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
    return NextResponse.json({ error: "Valid email is required" }, { status: 400 });
  }
  if (email.length > MAX_EMAIL_LEN) {
    return NextResponse.json(
      { error: `Email is too long (max ${MAX_EMAIL_LEN} characters).` },
      { status: 400 },
    );
  }
  if (!role || !isPacketRole(role)) {
    return NextResponse.json(
      { error: `Invalid role. Must be one of: ${PACKET_ROLES.join(", ")}` },
      { status: 400 },
    );
  }
  if (inviteeName && inviteeName.length > MAX_INVITEE_NAME_LEN) {
    return NextResponse.json(
      { error: `Name is too long (max ${MAX_INVITEE_NAME_LEN} characters).` },
      { status: 400 },
    );
  }

  // Refuse to invite a user who's already an active member of this account.
  // (Their current role can be changed via PATCH; no need for a duplicate
  // invite.)
  const existingUser = await prisma.user.findUnique({ where: { email } });
  if (existingUser) {
    const existingMembership = await prisma.teamMembership.findUnique({
      where: {
        userId_stripeCustomerId: {
          userId: existingUser.id,
          stripeCustomerId: accountId,
        },
      },
    });
    if (existingMembership && !existingMembership.revokedAt) {
      return NextResponse.json(
        { error: "This user is already an active member of this account." },
        { status: 409 },
      );
    }
  }

  // The unique (stripeCustomerId, email) index covers ALL statuses, so
  // "expire then create" would still collide. Upsert instead: any prior
  // invitation for (accountId, email) is overwritten with a fresh token,
  // role, expiry, and status='pending'.

  // If the inviter is an implicit Owner (no User row yet), materialize one
  // so we have a real userId to record on the invitation + audit log.
  let inviterUserId = auth.membership.userId;
  if (!inviterUserId) {
    const materialized = await materializeImplicitOwner({
      email: auth.payload.email,
      accountId,
      displayName: typeof auth.customer.name === "string" ? auth.customer.name : null,
    });
    inviterUserId = materialized.userId;
  }

  const token = randomBytes(32).toString("hex");
  const expiresAt = new Date(Date.now() + INVITATION_TTL_DAYS * 24 * 60 * 60 * 1000);

  const invitation = await prisma.teamInvitation.upsert({
    where: { stripeCustomerId_email: { stripeCustomerId: accountId, email } },
    update: {
      role,
      token,
      invitedByUserId: inviterUserId,
      inviteeName,
      expiresAt,
      acceptedAt: null,
      status: "pending",
    },
    create: {
      stripeCustomerId: accountId,
      email,
      role,
      token,
      invitedByUserId: inviterUserId,
      inviteeName,
      expiresAt,
      status: "pending",
    },
  });

  await prisma.teamAuditLog
    .create({
      data: {
        stripeCustomerId: accountId,
        actorUserId: auth.membership.userId,
        subjectUserId: null,
        action: "invite.sent",
        payload: JSON.stringify({ email, role }),
      },
    })
    .catch((err) => console.error("[POST invitations] audit log failed:", err));

  // Fire-and-forget invite email. If SMTP is broken the API still succeeds —
  // the full token is in the response body so the UI can show a copy-link
  // fallback. Surface emailSent in the response so the UI can warn.
  const accountLabel =
    (typeof auth.customer.name === "string" && auth.customer.name) ||
    auth.customer.email ||
    accountId;
  const inviterName =
    (typeof auth.customer.name === "string" && auth.customer.name) ||
    auth.payload.email;
  let emailSent = false;
  try {
    await sendTeamInviteEmail({
      to: email,
      roleDisplayName: ROLE_PERMISSIONS[role].displayName,
      inviterName,
      inviterEmail: auth.payload.email,
      accountLabel,
      token,
      expiresAt,
    });
    emailSent = true;
  } catch (err) {
    console.error("[POST invitations] email send failed:", err);
  }

  // Full token returned ONLY at creation time. UI may surface as copy-link
  // when emailSent is false.
  return NextResponse.json({
    emailSent,
    invitation: {
      id: invitation.id,
      email: invitation.email,
      role: invitation.role,
      token: invitation.token,
      expiresAt: invitation.expiresAt.toISOString(),
    },
  });
}
