// Ambient module declarations for static asset imports (*.png, *.jpg, *.svg, …).
//
// Next.js normally supplies these via next-env.d.ts, which carries
// `/// <reference types="next/image-types/global" />`. But next-env.d.ts is
// gitignored and only (re)generated by `next dev` / `next build`, so a fresh
// checkout that runs `tsc --noEmit` on its own — the CI type-check gate — has no
// image-module declarations and fails with TS2307 on `import x from '…/foo.png'`.
//
// Referencing Next's own image types here makes type-checking self-sufficient
// regardless of whether next-env.d.ts has been generated, and stays in sync with
// Next's StaticImageData typing. It dedupes cleanly when next-env.d.ts is also
// present locally (the same declarations are loaded once). See PA-273.
/// <reference types="next/image-types/global" />
